version: 0.2

phases:
    install:
        commands:
            #install Node 12
            - echo installing Node...
            - npm install
            - npm run build
            #install yarn
            - aws s3 cp build s3://$S3_BUCKET --recursive --exclude 'index.html'
            - aws s3 cp build/index.html s4://$S3_BUCKET
    